# Site settings
title: "HectorGuo's Blog"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hectorguo.com" # the base hostname & protocol for your site
tagline:          "The Tech & Life"
# Build settings
markdown: kramdown
kramdown:
    input: GFM
# markdown: redcarpet

# redcarpet: 
#     extensions:   ["fenced_code_blocks", "tables", "with_toc_data", "strikethrough", "underline", "footnotes"]
# highlighter:      pygments

# Permalinks
permalink:        /:categories/:title

# create sitemap
gems:
  - jekyll-sitemap

# css compressed
sass:
  style: compressed

weibo_appkey: "1908369758"

# i18n
author:
  zh: "郭海旭"
  en: "Hector Guo"
description: 
  zh: "Web前端开发者，致力于分享各类见闻，并将尚未翻译过的国外优秀文章以自己理解的方式分享出来，填充中文技术库"
  en: "A front-end developer, happy to share all the new ideas and methods about Web Development, Web Design and IT Management."
contacts:
  zh:
  -
    name: "微博"
    url: "http://weibo.com/hectorguo"
    icon: "&#xe809;"
  -
    name: "知乎"
    url: "http://www.zhihu.com/people/hectorguo"
    icon: "&#xe64c;"
  - 
    name: "Github"
    url: "https://github.com/hectorguo"
    icon: "&#xe735;"
  -
    name: "Linkedin"
    url: "https://www.linkedin.com/in/hectorguo"
    icon: "&#xe695;"
  en:
  -
    name: "Twitter"
    url: "https://twitter.com/hectorguo"
    icon: "&#xe8a8;"
  -
    name: "Github"
    url: "https://github.com/hectorguo"
    icon: "&#xe735;"
  -
    name: "Linkedin"
    url: "https://www.linkedin.com/in/hectorguo"
    icon: "&#xe695;"

paginate:         5

encoding:         utf-8

defaults:
  -
    scope:
      path: ""
    values:
      lang: zh
  -
    scope:
      path: _posts/en
    values:
      lang: en