# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            HectorGuo's Blog
tagline:          'The Tech Blog of HectorGuo'
description:      ''
url:              http://hectorguo.github.io

author:
  name:           'Hector Guo'
  url:            http://weibo.com/u/1829433861

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/hectorguo
<<<<<<< HEAD
encoding:         utf-8
=======
encoding:         utf-8
>>>>>>> e2c950cd590b532add6d22b23de2df57e2356d6a
