# Dependencies
markdown:         redcarpet
redcarpet: 
    extensions:   ["fenced_code_blocks", "tables", "with_toc_data", "strikethrough", "underline", "footnotes"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            HectorGuo's Blog
tagline:          'The Tech & Life'
description:      ''
url:              http://hectorguo.github.io

author:
  name:           'Hector Guo'
  url:            http://weibo.com/u/1829433861

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/hectorguo
encoding:         utf-8